# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: BuildTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release /property:CollectCoverage=True /property:CoverletOutputFormat=opencover
     
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.17
      with: 
        reports: 'coverage.opencover.xml'
        targetdir: ${{ vars.CODE_COVERAGE_DIR }}'
        reporttypes: 'Html;MarkdownSummary'
        sourcedirs: ''
        historydir: ''
        plugins: ''
        assemblyfilters: '-nunit*;-Dapper;'
        classfilters: '+*'
        filefilters: '-Program.cs;-*.cshtml'
        verbosity: 'Debug'

#        title: ${{ env.CODE_COVERAGE_REPORT_NAME }}
        tag: '${{ github.workflow}}_${{ github.run_id }}'
        customSettings: ''
        toolpath: 'reportgeneratortool'


    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2    
      with:
        name: Coverage Report
        path: ${{ vars.CODE_COVERAGE_DIR }}
        verbosit: 'Debug'
#   - name: Setup tmate session
#     if: success() || failure()
#     uses: mxschmitt/action-tmate@v3


# From https://github.com/im-open/code-coverage-report-generator